[0m23:17:05.579570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b38cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105937cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105964230>]}


============================== 23:17:05.583566 | c71df3b0-3b72-4df1-bbb7-3a9cdf982d62 ==============================
[0m23:17:05.583566 [info ] [MainThread]: Running with dbt=1.10.4
[0m23:17:05.583898 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/mohansaijasti/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init netflix', 'send_anonymous_usage_stats': 'True'}
[0m23:17:05.594415 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m23:17:05.599478 [info ] [MainThread]: 
Your new dbt project "netflix" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:17:05.599759 [info ] [MainThread]: Setting up your profile.
[0m23:21:45.335588 [info ] [MainThread]: Profile netflix written to /Users/mohansaijasti/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:21:45.367783 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 279.84308, "process_in_blocks": "0", "process_kernel_time": 0.363904, "process_mem_max_rss": "197738496", "process_out_blocks": "0", "process_user_time": 3.119164}
[0m23:21:45.368913 [debug] [MainThread]: Command `dbt init` succeeded at 23:21:45.368692 after 279.84 seconds
[0m23:21:45.370015 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056e9b80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11eb897f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11df31190>]}
[0m23:21:45.370710 [debug] [MainThread]: Flushing usage events
[0m23:21:45.650683 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:20:43.155548 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10644a240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1078ec710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1078ec440>]}


============================== 13:20:43.158596 | 68f6683c-d321-453c-add0-160a4887c155 ==============================
[0m13:20:43.158596 [info ] [MainThread]: Running with dbt=1.10.4
[0m13:20:43.158921 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/mohansaijasti/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:20:43.159236 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mohansaijasti/Documents/Data Engineering/DBT/netflixdbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:20:43.161148 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04427096, "process_in_blocks": "0", "process_kernel_time": 0.164508, "process_mem_max_rss": "109248512", "process_out_blocks": "0", "process_user_time": 0.713452}
[0m13:20:43.161515 [debug] [MainThread]: Command `dbt run` failed at 13:20:43.161460 after 0.04 seconds
[0m13:20:43.161730 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10644a240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10772e4e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1078b3e00>]}
[0m13:20:43.161903 [debug] [MainThread]: Flushing usage events
[0m13:20:43.544523 [debug] [MainThread]: An error was encountered while trying to flush usage events
